### ISSUE TITLE
Exception when multi touching

### ISSUE THREAD

**Issue by RaffiOhanian** [umano/AndroidSlidingUpPanel#233]
ArrayIndexOut of bounds Exception : length =1 index =1 at ViewDragHelper

**Comment by atetc** [comment]
This bug is actual for 3.1.1

Log: 
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime: FATAL EXCEPTION: main
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at com.sothree.slidinguppanel.ViewDragHelper.clearMotionHistory(ViewDragHelper.java:792)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at com.sothree.slidinguppanel.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1035)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at com.sothree.slidinguppanel.SlidingUpPanelLayout.onInterceptTouchEvent(SlidingUpPanelLayout.java:923)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1827)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(SlidingUpPanelLayout.java:946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1946)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1977)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1420)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.app.Activity.dispatchTouchEvent(Activity.java:2428)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1925)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.View.dispatchPointerEvent(View.java:7442)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3610)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3538)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4790)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4750)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4902)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:171)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4870)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4924)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:579)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:546)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:725)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:92)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:153)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5299)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
09-29 18:38:17.133 13689-13689/? E/AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:
