### ISSUE TITLE
Sliding panel resize problem

### ISSUE THREAD

**Issue by gargas** [umano/AndroidSlidingUpPanel#235]
![screenshot_2014-07-29-16-27-17 1](https://cloud.githubusercontent.com/assets/8299123/3734682/5705b748-171a-11e4-9a56-53409be82952.png)

![screenshot_2014-07-24-15-51-01](https://cloud.githubusercontent.com/assets/8299123/3734649/e8768262-1719-11e4-92c1-2435f6e76cce.png)

When i press select on map i collapse whole sliding layout to 0. But sometimes this happens. 

Moreover, in soft keyboard input mode , the panel doesnt resize properly and i dont want to use adjustPan. I tried using all the combinations but the problem remains the same

**Comment by barrtender** [comment]
I had the same (or very similar) problem when I was using "mSlidingPanel.setPanelHeight(0)" to hide it and "mSlidingPanel.setPanelHeight(168)" to show it.

My issue would only arise after I dragged to show the panel though. If I just clicked my map (to hide) then a marker (to show) I could go back and forth and it hid and showed great. However if I clicked a marker, slid the panel up, then slid it down and clicked the map I would get this dead space.

My problem was solved by using "                mSlidingLayout.setPanelState(SlidingUpPanelLayout.PanelState.HIDDEN);" to hide and "mSlidingLayout.setPanelState(SlidingUpPanelLayout.PanelState.COLLAPSED);" to show.

I have a feeling there's an issue where it needs to requestLayout for the children, but I couldn't figure it out.

**Comment by tokudu** [comment]
This is likely related to a buggy mapview. See https://github.com/umano/AndroidSlidingUpPanel/issues/341

**Comment by edumucelli** [comment]
I have the very same scenario than the one described by @kdk01, but using a MapFragment instead. sothree:umanoOverlay="true" works, but my ad banner, which is in the bottom of the first child, gets covered by the panel.

**Comment by LNSD** [comment]
I tink I've solved the issue with the EditText. As described by @kdk01, it happens when panel collapses while the keyboard is still opened.

<p align="center">
<img src="https://cloud.githubusercontent.com/assets/3949095/15796237/dd7ca4d6-29fa-11e6-9902-7160da00d59e.gif" width="200"> </p>

The solution was simple enough for me: mark the activity with `windowSoftInputMethod="adjustNothing"` in the Manifest and this resolved it.

``` xml
        <activity
            android:name=".main.MainActivity"
            android:label="@string/app_name"
            android:windowSoftInputMode="adjustNothing"  <-- This!
            android:theme="@style/AppTheme.NoActionBar">
           <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
```

This is the final result:

<p align="center">
<img src="https://cloud.githubusercontent.com/assets/3949095/15796312/27acba5e-29fc-11e6-968a-6ca7da3bc00d.gif" width="200"> </p>

Source: [Jeremy Wadsack - Android: Hide a view when the soft keyboard is showing](https://ballardhack.wordpress.com/2011/03/08/android-hide-a-view-when-the-soft-keyboard-is-showing/)

**Comment by RonyBrosh** [comment]
For me the problem was that inside activity it works and inside (nested) fragment with less available height the panel just won't collapse..

I've found that the bug was with the slidePanelAnchorPoint..
It should be set according to the available height in order to work...
I believe that the sliding panel should check the slidePanelAnchorPoint to make sure it's not over the general sliding panel height (which I believe caused the problem)...

**Comment by waqasyousafy** [comment]
where is the slution ????? am facing this too
