### ISSUE TITLE
EditText soft keyboard positioning

### ISSUE THREAD

**Issue by deronbrown** [umano/AndroidSlidingUpPanel#356]
Sample showing the issue: https://github.com/deronbrown/SlidingUpPanelIssue

An EditText within the main content view (second child) is expected to be repositioned above the soft keyboard when the keyboard appears. The behavior works as expected when the MainActivity is first launched. However, once interaction with the draggable view has occurred, the EditText's position will never be updated.

Notes:

* The activity's windowSoftInputMode is set to stateHidden|adjustResize. adjustResize is desired as to not hide the draggable view and toolbar when the keyboard is shown (as adjustPan would do).
* adjustPan behaves as expected both before and after interacting with the draggable view.
* An unrelated issue that was discovered in this sample is that only the EditText at the bottom of the activity fades when the draggable view is pulled down. Version 2.0.2 does not have this issue.

**Comment by deronbrown** [comment]
@tokudu This issue still appears in 3.0.0.

**Comment by scottmerritt** [comment]
Having the same issue in 2.0.2 and then tried to update in 3.0, but still faced with the problem.  I have a panel that I _sometimes_ want to show.  If I have adjustResize, display the keyboard to edit a field, then dismiss the keyboard, the panel will sometimes be shown on the screen.  It seems as though the screen resize caused the panel to move up, but it didn't get the message that the keyboard went away and now the panel should go back down since the activity has been resized to be larger again.

Is there not a way to tell it to entirely disable the panel?  I'm not putting anything in there, for this scenario, but setEnabled(false), hidePanel(), etc.  doesn't prevent it from appearing when the activity is resized.

**Comment by lacasrac** [comment]
It is a big issue. Is there any way to refresh view hierarchy after orientation changed or the soft keyboard is present?

**Comment by sajith666** [comment]
Happens for me also. The soft keyboard pushed up the sliding panel over the edit text

**Comment by KingWu** [comment]
Face the same issue
