### ISSUE TITLE
The list view in ScrollableView has some item cannot avaliable?

### ISSUE THREAD

**Issue by zhupengGitHub** [umano/AndroidSlidingUpPanel#642]
When I set the value of anchor point smaller than 1,The list view in ScrollableView has some item cannot avaliable

**Comment by charlesdurham** [comment]
This is because the sliding panel is partially offscreen. One solution is to hook into `onPanelSlide()` and resize your scrollView to be the height of the visible area of the sliding panel. The downside of this is you'll be performing lots of redraws because of `requestLayout()`. 

This is the only solution I was able to come up with, if anyone has anything cleaner please feel free to let me know :smile: 

```
@Override
public void onPanelSlide(View panel, float slideOffset) {
    Rect r = new Rect();
    panel.getGlobalVisibleRect(r);
    scrollView.getLayoutParams().height = r.height();
    scrollView.requestLayout();
```

**Comment by tokudu** [comment]
That sounds about right. I will file a separate issues to support something like that out of the box.
