### ISSUE TITLE
working with bottom navigation?

### ISSUE THREAD

**Issue by fukemy** [umano/AndroidSlidingUpPanel#942]
hi. Does your lib support show/hide bottom navigation like youtube?

**Comment by cheonjoosung** [comment]
& RelativeLayout

&& com.sothree.slidinguppanel.SlidingUpPanelLayout
&&&& Linearlayout   fragment 
&&& Linearlayout   slidingLayout 
&& com.sothree.slidinguppanel.SlidingUpPanelLayout

&& BottomNavigationView
& RelativeLayout

Above code works.
I think SlidingUpPanelLayout need root element.
The problem is fragment layout don't show when app started.
Change the tab and you will see...
But, you have to do this every time you launch the app

**Comment by fukemy** [comment]
bro, i ask this question 5 year ago, then i am not Android developer anymore
