### ISSUE TITLE
Ghosting/banding when Activity's windowBackground is set to @null

### ISSUE THREAD

**Issue by smithaaron** [umano/AndroidSlidingUpPanel#98]
I've implemented the AndroidSlidingUpPanel in my activity using the supplied demo code. After closing the panel it leave behind a banding effect. Screenshot attached.

Is this a bug or something I'm doing wrong? Same effect on 2012 Nexus 7 4.3 and Nexus 10 4.4.
![screenshot_2014-01-17-17-48-31](https://f.cloud.github.com/assets/5949562/1942913/0c013936-7fa1-11e3-9cab-5369bd2ccbcd.png)

**Comment by mohsin** [comment]
@tokudu May I ask which commit/where in the README is this issue mentioned? Also, I wonder why this issue occurs: windowBackground needs to be null in order to hide the section above the actions bars so as to allow fullscreen apps. Does that mean that this sliding up panel widget cannot be used in an activity using full screen theme such as splash screens?
